(executable
 (name postgresql_test)
 (modules postgresql_test)
 (libraries
  base
  lwt.unix
  pgocaml
  typed-sql
  typed-sql-pgocaml-lwt
  typed_sql_schema_test_codecs
  yojson
  ipaddr
  zarith)
 (preprocess
  (pps ppx_let)))

(executable
 (name prepare_bench)
 (modules prepare_bench)
 (libraries base lwt.unix pgocaml typed-sql typed-sql-pgocaml-lwt))
