(library
 (name typed_sql_private)
 (public_name typed-sql.private)
 (modules
  (:standard \ typed_sql))
 (libraries base ptime yojson zarith)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_let ppx_sexp_conv)))

(library
 (name typed_sql)
 (public_name typed-sql)
 (modules typed_sql)
 (libraries typed_sql_private)
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppx_sexp_conv)))
