(rule
 (alias runtest)
 (deps
  delete_requires_scope.ml
  foreign_column.ml
  left_join_requires_nullable_column.ml
  mismatched_expression.ml
  phantom_table_rows_are_distinct.ml
  private_ast_is_not_public.ml
  public_codec_view_is_hidden.ml
  public_parameter_constructor_is_hidden.ml
  public_parameters_are_hidden.ml
  public_command_parameters_are_hidden.ml
  public_decoder_is_hidden.ml
  public_shape_is_hidden.ml
  public_compiled_record_is_hidden.ml
  public_expr_constructor_is_hidden.ml
  public_identifier_is_abstract.ml
  public_projection_view_is_hidden.ml
  public_packed_type_is_hidden.ml
  public_template_constructor_is_hidden.ml
  run.sh
  select_is_required.ml
  update_requires_scope.ml
  wrong_ordering.ml)
 (action
  (run bash %{dep:run.sh} %{bin:ocamlfind} %{lib:typed-sql:typed_sql.cmi})))
